/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certificate1;

import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhushan
 */
public class Certificate extends javax.swing.JFrame {
Connection con= null;
Statement stmt = null;
ResultSet rs = null;
    /**
     * Creates new form Certificate
     */
    public Certificate() {
        initComponents();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jFrame3 = new javax.swing.JFrame();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel16.setText("DETAILS OF PARTICIPANTS");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 10, -1, 51));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 178, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 178, -1));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 178, -1));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 178, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 178, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 178, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 178, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SR NO.");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONTACT NO.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 151, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLASS");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 186, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BRANCH");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("WORKSHOP");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATE");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 294, -1, -1));

        jButton2.setText("CONTINUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 731, 224, 33));

        jButton7.setText("delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 635, 224, -1));

        jButton5.setText("insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 592, 224, -1));

        jButton6.setText("update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 592, 173, -1));

        jButton8.setText("empty");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 635, 185, -1));

        jButton10.setText("getdata");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 635, 173, -1));

        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 592, 185, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SRNO", "NAME", "CONTACT", "CLASS", "BRANCH", "WORKSHOP"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 340, 797, 218));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhushan\\Documents\\NetBeansProjects\\certificate1\\IMG\\Abstract-Blue-Hue-Wallpaper.jpg")); // NOI18N
        jLabel23.setText("jLabel22");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 1060));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame2.getContentPane().setLayout(new javax.swing.BoxLayout(jFrame2.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(null);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(870, 10, 209, 22);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(300, 110, 216, 30);
        jPanel4.add(jTextField11);
        jTextField11.setBounds(300, 150, 216, 30);
        jPanel4.add(jTextField14);
        jTextField14.setBounds(300, 200, 216, 27);
        jPanel4.add(jTextField19);
        jTextField19.setBounds(300, 252, 160, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("NAME");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(25, 117, 100, 28);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("WORKSHOP");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(22, 159, 150, 29);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("CONDUCTED BY");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(22, 206, 230, 28);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("DATE");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(20, 260, 100, 22);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel13.setText(" FILL NAMES OF CERTIFYING AUTHORITIES");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(22, 322, 330, 17);
        jPanel4.add(jTextField13);
        jTextField13.setBounds(22, 387, 161, 32);
        jPanel4.add(jTextField15);
        jTextField15.setBounds(212, 387, 171, 32);
        jPanel4.add(jTextField16);
        jTextField16.setBounds(415, 387, 167, 32);
        jPanel4.add(jTextField18);
        jTextField18.setBounds(609, 387, 172, 32);

        jButton4.setText("GENERATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(100, 507, 244, 34);

        jButton12.setText("CLOSE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(410, 505, 172, 34);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SR NO.");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(770, 10, 70, 22);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhushan\\Documents\\NetBeansProjects\\certificate1\\IMG\\qwer.jpg")); // NOI18N
        jLabel21.setText("jLabel20");
        jLabel21.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel21.setMinimumSize(new java.awt.Dimension(1150, 690));
        jLabel21.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel4.add(jLabel21);
        jLabel21.setBounds(-80, -50, 1450, 900);

        jFrame2.getContentPane().add(jPanel4);

        jScrollPane5.setViewportView(jTextPane1);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhushan\\Documents\\NetBeansProjects\\certificate1\\IMG\\Abstract-Blue-Hue-Wallpaper.jpg")); // NOI18N
        jLabel22.setText("jLabel22");

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(905, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 330, 213, 40);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 240, 82, 41);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(490, 240, 221, 41);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(490, 160, 221, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 160, 82, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhushan\\Documents\\NetBeansProjects\\certificate1\\IMG\\images.png")); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 140, 200, 238);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     CERTIFICATE GENERATION SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(165, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(255, 25));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, 40, 910, 41);

        jButton9.setText("SIGN UP");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(610, 330, 100, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhushan\\Documents\\NetBeansProjects\\certificate1\\IMG\\48071.jpg")); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(-330, 0, 1210, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
         
          
          
          
         try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            Statement stmt =con.createStatement();
            String query="SELECT * FROM login  WHERE password=" + jTextField12.getText()+ ";"  ;
          rs = stmt.executeQuery(query);
          if ( rs.next()){
               String loginid = rs.getString("loginid");
              String password = rs.getString("password");
              
                
               jTextField10.setText(loginid);
                jTextField12.setText(password);
                
                
               JOptionPane.showMessageDialog(null, "login succesful");
               jFrame1.setSize(1000,1000);
                jFrame1.setVisible(true);
                
            } else{
                JOptionPane.showMessageDialog(null, "PLEASE SIGN UP");
           }
       } catch (Exception e){
           JOptionPane.showMessageDialog(null,"error in connectivity");
        
           
   }  
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       jFrame1.setVisible(false);
        jFrame2.setSize(1350,900);
        int srno;
        srno=Integer.parseInt(jTextField4.getText());
        jTextField8.setText(""+srno);
        String name= jTextField1.getText();
        jTextField9.setText("Mr/Mrs "+name);
         String workshop= jTextField6.getText();
        jTextField11.setText(""+workshop);
         String date= jTextField7.getText();
        jTextField19.setText(""+date);
         jFrame2.setVisible(true);
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       // jTextArea2.setEditable(false);
        
        Document pdfdoc= new Document();
        try{
             PdfWriter.getInstance(pdfdoc,new FileOutputStream("PDF printing with java.pdf"));
                 pdfdoc.open();
             
             
         
            
             Font StyleHeading1 = new Font(Font.FontFamily.COURIER,25,Font.BOLD);
              Font StyleHeading2 = new Font(Font.FontFamily.HELVETICA,25,Font.BOLD , BaseColor.BLUE);
              Paragraph reportTitle8 = new Paragraph(jTextField8.getText());
             Paragraph reportTitle1 = new Paragraph("CSI PCE\n" +"certificate \n" +"of appreciation\n" +"This is to certify that",StyleHeading2);
             Paragraph reportTitle2 = new Paragraph(jTextField9.getText(),StyleHeading1);
                Paragraph reportTitle7 = new Paragraph("has participated in a workshop\n"+jTextField11.getText(),StyleHeading1);
           //  Paragraph reportTitle3= new Paragraph(jTextField11.getText(),StyleHeading1);
             Paragraph reportTitle4 = new Paragraph("by\n"+jTextField14.getText(),StyleHeading1);
             
             Paragraph reportTitle6 = new Paragraph("\nconducted on\n"+jTextField19.getText(),StyleHeading1);
             
             
            // Paragraph paraDemo1 = new Paragraph(jTextArea1.getText());
             
              Paragraph paraDemo2 = new Paragraph("\n\n\n"+jTextField13.getText()+"    \t    "+jTextField15.getText()+"    \t    " +jTextField16.getText()+"    \t    "+jTextField18.getText());
               
              
             
      //       Paragraph paraDemo = new Paragraph(jTextField10.getText());
             
         //     Paragraph paraDemo2 = new Paragraph(jTextField16.getText() );
              reportTitle8.setAlignment(Element.ALIGN_LEFT);
              reportTitle1.setAlignment(Element.ALIGN_CENTER);
              reportTitle2.setAlignment(Element.ALIGN_CENTER);
           //   reportTitle3.setAlignment(Element.ALIGN_CENTER);
              reportTitle4.setAlignment(Element.ALIGN_CENTER);
              reportTitle7.setAlignment(Element.ALIGN_CENTER);
              reportTitle6.setAlignment(Element.ALIGN_CENTER);
              paraDemo2.setAlignment(Element.ALIGN_CENTER);
             // paraDemo1.setAlignment(Element.ALIGN_CENTER);
              
                          pdfdoc.add(reportTitle8);
                          pdfdoc.add(reportTitle1); 
                          pdfdoc.add(reportTitle2); 
                          pdfdoc.add(reportTitle7); 
                        //  pdfdoc.add(reportTitle3); 
                           pdfdoc.add(reportTitle4); 
                          pdfdoc.add(reportTitle6); 
                          
                      //    pdfdoc.add(paraDemo1);
                           pdfdoc.add(paraDemo2);
                       //    pdfdoc.add(paraDemo);
                        //    pdfdoc.add(paraDemo2);
                        
              pdfdoc.setPageSize(PageSize.A4);
             pdfdoc.close();
        }catch (DocumentException e) {
            e.printStackTrace();
        }catch (FileNotFoundException e){
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(null,"certificate is successfully generated");
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            Statement stmt =con.createStatement();
            String query="SELECT * FROM certificate ; " ;
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                String SRNO = rs.getString("SRNO");
                String NAME = rs.getString("NAME");
                String ACAD = rs.getString("ACAD");
                String NOO = rs.getString("NOO");
                
                String NOH = rs.getString("NOH");
                String NOC = rs.getString("NOC");
                
                model.addRow(new Object[]{SRNO,NAME,ACAD,NOO,NOH,NOC});
            }
            rs.close();
            stmt.close();
            con.close();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error in Connetivity");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        int rows = model.getRowCount();
        if (rows>0){
            for(int i = 0 ; i<rows ; i++) {
                model.removeRow(0);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            Statement stmt =con.createStatement();
            String query="SELECT * FROM certificate  WHERE SRNO=" + jTextField4.getText()+ ";"  ;
            rs = stmt.executeQuery(query);
            if ( rs.next()){
                String NAME = rs.getString("NAME");
                String ACAD = rs.getString("ACAD");
                String NOO = rs.getString("NOO");
                String NOH = rs.getString("NOH");
                String NOC = rs.getString("NOC");
                jTextField1.setText(NAME);
                jTextField2.setText(ACAD);
                jTextField3.setText(NOO);
                jTextField5.setText(NOH);
                jTextField6.setText(NOC);
            } else{
                JOptionPane.showMessageDialog(null, "No such record found");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"error in connectivity");
            
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String x = jTextField4.getText();
        String y = jTextField1.getText();
        String z = jTextField2.getText();
        String w = jTextField3.getText();
        String m = jTextField5.getText();
        String n = jTextField6.getText();
        String INSERT = "INSERT INTO certificate  VALUES("+x+",'"+y+"',"+z+",'"+w+"','"+m+"','"+n+"')";
            
        
        
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            
            Statement stmt = con.createStatement();
            
            
            stmt.executeUpdate(INSERT);
            JOptionPane.showMessageDialog(null, "Record Successfully Added");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"error in connectivity");
            
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
             try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            stmt = con.createStatement();
            String query = "UPDATE certificate SET NAME= '"+jTextField1.getText()+"', ACAD = "+jTextField2.getText()+", NOO = '"
                    +jTextField3.getText()+"',NOH ='"+jTextField5.getText()+"',NOC = '"+jTextField6.getText()+ "'  WHERE SRNO = "+jTextField4.getText()+" ;" ;
            
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Record Successfully updated");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"error in connectivity");
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            stmt = con.createStatement();
            String query = "DELETE FROM certificate   WHERE SRNO = "+jTextField4.getText()+" ;" ;
            
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Record Successfully deleted");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"error in connectivity");
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        String x = jTextField10.getText();
        String y = jTextField12.getText();
        
        
        String INSERT = "INSERT INTO Login VALUES('"+jTextField10.getText()+"','"+jTextField12.getText()+ "');";
           
                 
            
        
        
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/certificate","root","BHUSHAN@1999");
            
            Statement stmt = con.createStatement();
            
            
            stmt.executeUpdate(INSERT);
            JOptionPane.showMessageDialog(null, "successfully signed in");
            JOptionPane.showMessageDialog(null, "please login to proceed");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"enter valid password");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Certificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
